# Generated by Django 4.1.4 on 2022-12-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=32, null=True)),
                ('username', models.CharField(default=None, max_length=256, null=True)),
                ('email', models.EmailField(default=None, max_length=256, null=True)),
                ('website', models.CharField(default=None, max_length=256, null=True)),
            ],
        ),
    ]
